version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: build1
      env:
        variables:
          BUILD_ID: build1
    - identifier: build2
      buildspec: build2.yml
      env:
        variables:
          BUILD_ID: build2

env:
  compute-type: BUILD_GENERAL1_SMALL

phases:
  build:
    commands:
      - printenv
      - echo 'Running default build'
      - echo 'BUILD_ID =' $BUILD_ID
